### ISSUE TITLE
Automatically Lock the Login Keychain

### ISSUE THREAD

**Issue by randyqx** [ernw/hardening#3]
I did the Automatically Lock the Login Keychain thing.  It makes me crazy, asking for my loooong passphrases way too frequently.  I went to Keychain Access selected the login Keychain, and turned it off.  I still get prompted for ssh passphrases, ScanSnap, blah blah blah.  How do I really stop this?

**Comment by Traxes** [comment]
Hello randyqx,

to completely disable the popups you have to Export the Keychain to a file. Delete everything. Create a new keychain (With disabled Settings) and import it again -> [Import/Export Keychain](https://support.apple.com/kb/PH20120?locale=en_US).

you can also minimize the Popups to only appear after a reboot or hibernate by changing the settings of the "Change Settings for Keychain 'Login' " to only enable "Lock when sleeping" and uncheck "Set Lock after [...] minutes of inactivity to 10".

Cheers,

Traxes

**Comment by randyqx** [comment]
this got me in the right neighborhood.  i could not actually export (greyed out), but i could copy the file out.  i had to bludgeon it a bit, but it finally succumbed.  thanks.
